### PR TITLE
Fixes eslint reports and formats. Closes #290

### LINKED ISSUE #290: Not allowing commits due to eslint errors
Trying to do a commit in my fork of this repository will produce

```sh
$ git commit -m "Removes # from Stewards list. Closes #269" -a                                 
✔ Preparing lint-staged...              
⚠ Running tasks for staged files...                                                                                                                             
  ❯ package.json — 1 file                                                                                                                                       
    ❯ packages/app/**/*.{ts,tsx} — 1 file                                       
      ✖ yarn workspace @gooddollar/goodcollective-app lint --fix [FAILED]                                                                                       
      ◼ yarn workspace @gooddollar/goodcollective-app format                                                                                                    
    ↓ packages/sdk-js/**/*.{ts,tsx} — no files                                  
↓ Skipped because of errors from tasks.                                                                                                                         
✔ Reverting to original state because of errors...                                                                                                              
✔ Cleaning up temporary files...        
                                                                                                                                                                
✖ yarn workspace @gooddollar/goodcollective-app lint --fix:                                                                                                     

/home/vtamara/comp/gooddollar/GoodCollective/packages/app/src/components/DonateComponent.tsx
  58:31  warning  'type' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

home/vtamara/comp/gooddollar/GoodCollective/packages/app/src/components/Header/ConnectWalletMenu.tsx                                                           
  7:35  warning  'props' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars                                     
                                                                                                                                                                
/home/vtamara/comp/gooddollar/GoodCollective/packages/app/src/components/TransactionList/TransactionList.tsx                                                    
  1:29  warning  'Platform' is defined but never used  @typescript-eslint/no-unused-vars                                                                      
                                        
/home/vtamara/comp/gooddollar/GoodCollective/packages/app/src/components/ViewCollective.tsx                                                                     
  56:26  warning  'isMobileView' is assigned a value but never used  @typescript-eslint/no-unused-vars                                                          
                                                                                
/home/vtamara/comp/gooddollar/GoodCollective/packages/app/src/components/WalletCards/DonorCollectiveCard.tsx                                                    
  30:3  warning  'isDesktopResolution' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars                       
                                                                                
/home/vtamara/comp/gooddollar/GoodCollective/packages/app/src/components/WalletCards/StewardCollectiveCard.tsx                                                  
  25:3  warning  'isDesktopResolution' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars                       
                                        
/home/vtamara/comp/gooddollar/GoodCollective/packages/app/src/hooks/useApproveSwapTokenCallback.ts                                                              
  40:6  error  React Hook useEffect has a missing dependency: 'refetch'. Either include it or remove the dependency array  react-hooks/exhaustive-deps          

✖ 7 problems (1 error, 6 warnings)                                                                                                                              
                                                                                                                                                                
husky - pre-commit hook exited with code 1 (error) 
```

### PR DESCRIPTION
**Pull request by vtamara**
# Description

About #290

# How Has This Been Tested?

By running `yarn workspace  gooddollar/goodcollective-app lint`

# Checklist:
- [X] PR title matches follow: (Feature|Bug|Chore) Task Name
- [X] My code follows the style guidelines of this project
- [X] I have followed all the instructions described in the initial task (check Definitions of Done)
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have added reference to a related issue in the repository
- [X] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [X] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

### What change is being made?
Fix ESLint issues and ensure code formatting consistency throughout the codebase.

### Why are these changes being made?
Consistent code formatting and resolving ESLint issues enhance code readability, maintainability, and adhere to coding standards, thus ensuring a cleaner and more professional codebase. These changes also address formatting errors that could potentially cause runtime complexities and allow for seamless integration with automated linting and formatting tools.

> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`

### CODE REVIEW

File: packages/app/src/components/ViewCollective.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ const HasDonatedCard = ({
 }) => {
   const { address } = useAccount();
   const { data: ensName } = useEnsName({ address, chainId: 1 });
-  const { isDesktopView, isMobileView } = useScreenSize();
+  const { isDesktopView /*, isMobileView*/ } = useScreenSize();
```
Comment (L03TJ3) [inline packages/app/src/components/ViewCollective.tsx:56]:
```suggestion
  const { isDesktopView } = useScreenSize();
```

**Comment by L03TJ3** [comment]
@vtamara Thanks for this, merging
